#
# Copyright 2009-2011 Freescale Semiconductor, Inc.
#
# SPDX-License-Identifier:	GPL-2.0+
#

#obj-y += dtsec.o
obj-y += eth.o
obj-y += fm.o
obj-y += init.o

# Soc have FMAN v3 with mEMAC
obj-y += memac.o
