obj-y += phy.o mdio_bus.o
obj-$(CONFIG_AR8327N_PHY)	+= ar8327.o
obj-$(CONFIG_AT803X_PHY)	+= at803x.o
obj-$(CONFIG_LXT_PHY)		+= lxt.o
obj-$(CONFIG_MARVELL_PHY)	+= marvell.o
obj-$(CONFIG_MICREL_PHY)	+= micrel.o
obj-$(CONFIG_NATIONAL_PHY)	+= national.o
obj-$(CONFIG_REALTEK_PHY)	+= realtek.o
obj-$(CONFIG_SMSC_PHY)		+= smsc.o
obj-$(CONFIG_MV88E6XXX_PHY)	+= mv88e6xxx.o

obj-$(CONFIG_MDIO_MVEBU)	+= mdio-mvebu.o
obj-$(CONFIG_MDIO_MEMAC)	+= mdio-memac.o
obj-$(CONFIG_MDIO_SMI)		+= mdio-smi.o
obj-$(CONFIG_MDIO_BITBANG)	+= mdio-bitbang.o
obj-$(CONFIG_MDIO_GPIO)		+= mdio-gpio.o
