#!/bin/sh

addpart -n /dev/ram0 128M@128M(ramload)
addpart /dev/ramload 512k@0(barebox)

addpart -n /dev/nor0 56M@000(primary)
addpart -n /dev/nor0 56M@56M(secondary)
addpart -n /dev/nor0 15M@112M(config)
